version: '3'
services:
    rails-server:
        container_name: "rails-server"
        build:
            context: .
            args:
                APP_ROOT: $APP_ROOT
        tty: true
        stdin_open: true
        env_file:
            -   '.env'
        volumes:
            -   '.:${APP_ROOT}'
        ports:
            -   '3000:3000'
        links:
            -   'mysql-server'
    #DB
    mysql-server:
        container_name: "mysql-server"
        image:  'mysql:5.7'
        volumes:
            -   './sql:/docker-entrypoint-initdb.d'
        environment:
            MYSQL_ROOT_PASSWORD: pass